version: "3.8"

services:
  app:
    build:
      context: .
      target: prod

    stop_signal: SIGINT

    command: ["python3", "-m", "app", "-H", "0.0.0.0", "-P", "80"]

    ports:
      - 80:80

    depends_on:
      - mongo

    env_file:
      .env

  mongo:
    image: mongo:4.2-bionic

#     volumes:
#       - ./mongo_db:/data/db  # To make mongo persistent
